merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/<int:band_id>/change/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),
    path('bands/add/', views.band_create, name='band-create'),
    path('about/', views.about),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('listings/<int:listing_id>/change/', views.listing_update, name='listing-update'),
    path('listings/<int:listing_id>/delete/', views.listing_delete, name='listing-delete'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/<int:contactus_id>/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

import textwrap

# Create your models here.
class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'



class Listing(models.Model):
    class Type(models.TextChoices):
        DISQUES = 'R'
        VETEMENTS = 'C'
        AFFICHES = 'P'
        DIVERS = 'M'

    name = models.fields.CharField(max_length=100)    
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)], null=True, blank=True)
    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        length=22
        suffix='...'
        if len(self.description) <= length:
            return f'{self.name} ({self.description})'
        else:
            lines = textwrap.wrap(self.description, length-3, break_long_words=False)
            desc = lines[0] + ("..." if len(lines)>1 else "")
            return f'{self.name} ({desc})'
            # return ' '.join(self.description[:length+1].split(' ')[0:-1]) + suffix


class ContactUsDatas(models.Model):
    name = models.fields.CharField(max_length=100)
    email = models.fields.EmailField()
    message = models.fields.CharField(max_length=1000)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)



class BandForm(forms.ModelForm):
   class Meta:
     model = Band
     fields = '__all__'


class ListingForm(forms.ModelForm):
   class Meta:
     model = Listing
     fields = '__all__'

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail

from listings.models import Band, Listing, ContactUsDatas
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.shortcuts import redirect 



def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, band_id):
    band = get_object_or_404(Band, pk=band_id)
    return render(request, 'listings/band_detail.html', {'band': band})


def band_update(request, band_id):
    band = get_object_or_404(Band, pk=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request, 'listings/band_update.html', {'form': form})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)

    else:
        form = BandForm()

    return render(request,
            'listings/band_create.html',
            {'form': form})


def band_delete(request, band_id):
    band = get_object_or_404(Band, pk=band_id)
    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')
    
    return render(request, 'listings/band_delete.html', {'band': band})



def about(request):
    return render(request, 'listings/about.html')



def listing_list(request):
    titles = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'titles': titles})


def listing_detail(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    return render(request, 'listings/listing_detail.html', {'listing': listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer un nouveau « Listing » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('listing-detail', listing.id)

    else:
        form = ListingForm()

    return render(request,
            'listings/listing_create.html',
            {'form': form})


def listing_update(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le listing existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du listing que nous venons de mettre à jour
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request, 'listings/listing_update.html', {'form': form})


def listing_delete(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    if request.method == 'POST':
        # supprimer le listing de la base de données
        listing.delete()
        # rediriger vers la liste des listings
        return redirect('listing-list')
    
    return render(request, 'listings/listing_delete.html', {'listing': listing})




def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            datas = ContactUsDatas.objects.create(name=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                                                    email=form.cleaned_data['email'],
                                                    message=form.cleaned_data['message'],)
            send_mail(
                    subject=datas.name,
                    message=datas.message,
                    from_email=datas.email,
                    recipient_list=['admin@merchex.xyz'],
                )
            return redirect('email-sent', contactus_id=datas.id)
        else:
            dummy = 0
        # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
        # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()
    
    return render(request, 'listings/contact.html', {'form': form})


def email_sent(request, contactus_id):
    contactusdatas = get_object_or_404(ContactUsDatas, pk=contactus_id)
    return render(request, 'listings/email_sent.html', {'contactusdatas': contactusdatas})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>a propos</h1> <p>nous adorons merch !</p>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes : Création d'un nouveau groupe</h1>

<form action="" method="post" validate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
  </form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer">
</form>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
   {% if band.official_homepage %}
     <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
   {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>

<a href="{% url 'band-delete' band.id %}">Effacer ce groupe</a>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
    {% for band in bands %}
        <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
             - <a href="{% url 'band-update' band.id %}">[modifier]</a>
             - <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes : Mise à jour d'un groupe</h1>

<form action="" method="post" validate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
  </form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>

        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Liste</a>
            <a href="{% url 'contact' %}">Contact</a>
        </nav>
        
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>contact us</h1>

        <ul>
                <li>name : {{ contactusdatas.name }}</li>
                <li>email : {{ contactusdatas.email }}</li>
        </ul>

        <p>Message : {{ contactusdatas.message }}</p>



        <p>Email envoyé.</p>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes : Création d'un nouveau listing</h1>

<form action="" method="post" validate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
  </form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Supprimer le listing</h1>

<p>Etes-vous sûr de vouloir supprimer le listing : {{ listing.name }} ?</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer">
</form>

<a href="{% url 'listing-list' %}">Retour à tous les listings</a>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ listing.name }}</h2>

<ul>
 <li>Type : {{ listing.get_type_display }}</li>
 <li>Année : {{ listing.year }}</li>
 <li>Vendu : {{ listing.sold|yesno }}</li>
 <li>Groupe : {{ listing.band.name }}</li>
</ul>

<p>{{ listing.description }}</p>

<a href="{% url 'listing-update' listing.id %}">Modifier ce listing</a>

<a href="{% url 'listing-delete' listing.id %}">Supprimer ce listing</a>

<a href="{% url 'listing-list' %}">Retour à tous les listings</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>listings</h1>

        <a href="{% url 'listing-create' %}">Créer un nouveau listing</a>

        <!-- 
        <p>Mes {{ titles|length }} titres préférés sont :</p>
        -->
        <!-- TODO : liste des titres -->
        <ul>
            {% for title in titles %}
                <!-- <li>{{ title.name|lower }}</li> -->
                <li><a href="{% url 'listing-detail' title.id %}">{{ title.name }}</a>
                    - <a href="{% url 'listing-update' title.id %}">[modifier]</a>
                    - <a href="{% url 'listing-delete' title.id %}">[supprimer]</a>
                </li>
            {% endfor %}
        </ul>
{% endblock %}    

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Listing : Mise à jour d'un nouveau listing</h1>

<form action="" method="post" validate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
  </form>

{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>listings</h1>
        <p>Mes {{ titles|length }} titres préférés sont :</p>
        <!-- TODO : liste des titres -->
        <ul>
            {% for title in titles %}
                <li>{{ title.name|lower }}</li>
            {% endfor %}
        </ul>
{% endblock %}    